version: "3.9" 
services:
  db:
    image: mongo
    container_name: dbmongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: madmin
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - /home/david/Documentos/Volumenes/mongoc:/data/db
    networks:
      - practica1-net

  backend:
    image: davdprado/backen_p1_201807420
    container_name: backend
    environment:
      MONGO_HOST: db
    ports:
    - "8080:8080"
    restart: always
    depends_on:
    - db
    networks:
    - practica1-net

  frontend:
    image: davdprado/frontend_p1_201807420
    container_name: frontend
    ports:
    - "80:80"
    restart: always
    depends_on:
    - backend
    networks:
    - practica1-net
  
volumes:
  mongodata:

networks:
  practica1-net:
    name: "practica1-net"
    driver: bridge